# Configurations
title:            prooph board Wiki
longtitle:        prooph board Wiki
author:           prooph software GmbH
email:            contact@prooph-board.com
description: >
  prooph board FAQs, documentation and guides.

version:          1.0
gitbook_version:  3.2.3

url:              'https://wiki.prooph-board.com'
baseurl:          ''

toc:
  enabled: true
  h_min: 1
  h_max: 3

collections:
  cody_php_tutorial:
    output: true
  cody_node_tutorial:
    output: true
  board_workspace:
    output: true
  access_management:
    output: true

gitbook_search:
  include:
    pages: true
    collections:
      - board_workspace
      - access_management
      - cody_node_tutorial
      - cody_php_tutorial


# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:title:output_ext

exclude:
  - _drafts

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jemoji
